### ISSUE TITLE
In tgb-flight dataset, what does it means for the flight to have the same src & dst?

### ISSUE THREAD

**Issue by HorHang** [shenyangHuang/TGB#74] opened 2023-12-27 11:22 UTC
![image](https://github.com/shenyangHuang/TGB/assets/103940969/9f964566-5de0-4b0c-a4ea-82bcda7525e1)

**Comment by shenyangHuang** [comment] 2023-12-27 17:02
Hi,

Thanks for your interest in our work, the data source of `tgbl-flight` is a crowd sourced dataset, thus the data source can be noisy. In this case, this could be an issue left over from the crowd sourcing and seen as noise. Probably because either the source or destination was not observed correctly,  yet the flight route (callsign) and type code is observed. 

Best,
Andy

**Comment by shenyangHuang** [comment] 2024-01-09 16:32
closing the comment as the issue is answered

**Closed** 2024-01-09 16:32 UTC
