### ISSUE TITLE
Problem with tgbl-flight

### ISSUE THREAD

**Issue by YanivDorGalron** [shenyangHuang/TGB#79] opened 2024-02-27 21:13 UTC
using py-tgb 0.9.2 and the following code:
`dataset = PyGLinkPropPredDataset(name="tgbl-flight", root="datasets")`

i get the following error:
`File not found at /home/ygalron/anaconda3/lib/python3.11/site-packages/tgb/datasets/tgbl_flight/tgbl-flight_edgelist_v2.csv`

in the folder `/home/ygalron/anaconda3/lib/python3.11/site-packages/tgb/datasets/tgbl_flight` exists 2 files: 
1. a tgbl-flight.zip
2. a tgbl-flight folder (which contains the missing csv)

a solution to that from my end was copying the files from:
`/home/ygalron/anaconda3/lib/python3.11/site-packages/tgb/datasets/tgbl_flight/tgbl_flight/*`
to
`/home/ygalron/anaconda3/lib/python3.11/site-packages/tgb/datasets/tgbl_flight/`

**Comment by shenyangHuang** [comment] 2024-02-29 01:47
Hi,

Thanks for reporting this issue, this is due to a redundant folder (`tgbl_flight/`) in the zipped file. I have uploaded a new version of the dataset. 

No code changes are needed, if you remove your existing `datasets/tgbl_flight` and redownload the dataset, it would work as intended. However, the files are the same, so feel free to keep your current folder and use it. 

Best,
Andy

**Comment by shenyangHuang** [comment] 2024-03-22 19:43
closing issue as it is resolved

**Closed by shenyangHuang** 2024-03-22 19:43 UTC
Labels: bug
